### ISSUE TITLE
Some snd sounds not recognised

### ISSUE THREAD

**Issue by gingerbeardman** [andrews05/ResForge#10]
![Screen shot 2023-08-17 at 21 50 45](https://github.com/andrews05/ResForge/assets/49612/d346fd7b-f9d4-4852-a3aa-9cf98af62e41)

The file in question is included in the disk image on this page: https://archive.org/details/thoru-yamamoto-hypercard-stacks

**Comment by andrews05** [comment]
Thanks for the report, would you mind attaching the file here? SheepShaver is hanging for me when I try to mount the disk image 🫤

Note ResForge currently only supports sampled sounds, not synth.

**Comment by andrews05** [comment]
I managed to get the file, and I've just pushed a commit to fix it: 598765c
(No ETA on the next release though, sorry)

**Comment by gingerbeardman** [comment]
cheers and thanks! Of course I'm not in a rush for a new release.

**Comment by andrews05** [comment]
This is now published in v1.4: https://github.com/andrews05/ResForge/releases

**Comment by gingerbeardman** [comment]
Thanks! 

ps: Last night I was reading https://mace.software/2023/08/31/summer-23-update/ which mentions at least two versions of '`snd `' resources and three versions of Sound Manager. This was all news to me, I didn't remember any of those details from back in the day.

> - Added support for version 2 ‘snd ‘ resources in Sound Manager 2.x SndPlay – these were used by Capitalist Pig game

**Comment by andrews05** [comment]
Yeah, I had to learn a lot about 'snd ' resources when I made the sound editor 😄
I believe version 2 was primarily for HyperCard. Version 1 always remained the standard/default format.
The 'toybell' sound that wasn't working was a version 2 format, but the reason it didn't work was because it uses a different command code 'soundCmd' rather than than usual 'bufferCmd'.

**Comment by gingerbeardman** [comment]
Thanks for the info!
