### ISSUE TITLE
PXM# Support

### ISSUE THREAD

**Issue by 1davi** [andrews05/ResForge#11]
The pxm# images are not loading, I can only see the filenames
Here is a comparison with ThemePark:
<img width="1719" alt="Screenshot 2024-02-09 at 01 56 56" src="https://github.com/andrews05/ResForge/assets/14959546/7d87f8e8-bcde-4aa5-90bc-ba648da59d1e">

**Comment by andrews05** [comment]
Hi, thanks for the report.
pxm# is not currently known by ResForge, would you mind posting some sample resources so I can look into adding support?

**Comment by 1davi** [comment]
Here
[Extras.rsrc.zip](https://github.com/andrews05/ResForge/files/14217658/Extras.rsrc.zip)

**Comment by andrews05** [comment]
Great, thank you! I'll see what I can do...

**Comment by andrews05** [comment]
I wasn't able to find any documentation on it so I've attempted to just figure it out by hand. I've pushed a commit which seems to successfully decode all the ones in the above file.
<img width="757" alt="Screen Shot 2024-02-09 at 9 06 25 PM" src="https://github.com/andrews05/ResForge/assets/4584038/026941bc-7e1f-4f7f-a7f1-4bacb2859d59">

**Comment by 1davi** [comment]
I wasn’t able to test because I failed at using Xcode, something about hexfiend framework missing.
But I trust in your skills, thank you

**Comment by andrews05** [comment]
Ah, you probably need to run `git submodule update --init` to checkout HexFiend and Graphite.

The next release of ResForge may still be a few weeks away, though I could post a dev build for you if you need?

**Comment by 1davi** [comment]
Yes, please

**Comment by andrews05** [comment]
[edit:removed]
As this is a dev build you may notice it's a little slower at some things.
Let me know if you have any issues with pxm# resources.
