### ISSUE TITLE
Ability to extract a image resource into binary file

### ISSUE THREAD

**Issue by wiesmann** [andrews05/ResForge#15]
Hi,

it would be very convenient to be able to allow the export of any arbitrary resource as a simple binary file. 
Basically, when you select any resource, `Export` would also allow for binary export for pict and icons files. 
I want the PICT data, not a TIFF version thereof. 

There is a workaround: open the resource in the hex-editor, copy-paste it into HexFiend…
Maybe the export option should also be present in the hex editor.

**Comment by andrews05** [comment]
Hi @wiesmann, thanks for the suggestion. I can certainly look at adding a more "raw" export...

**Comment by andrews05** [comment]
I've pushed a change to add this feature. Hold option to use the "Export raw..." menu item, which will export the resource data directly. You can use this from the document window or any editor.

**Comment by wiesmann** [comment]
Thanks a lot!

**Comment by andrews05** [comment]
Sorry for the wait, this is now released in v1.4.2 🙂
