### ISSUE TITLE
Build fails on Xcode 12.4: "variable used within its own initial value"

### ISSUE THREAD

**Issue by ghost** [andrews05/ResForge#6]
The following lines of code cause a compilation error on Xcode 12.4 on OS X 10.15.7.
https://github.com/andrews05/ResForge/blob/1c9ab5db6e19beda6c090e6b41a51f4d014b9825/ResForge/Classes/ResourceDocument.swift#L186-L189

We get the message "variable used within its own initial value."

The following steps were taken:
1. Clone ResForge with git
2. Run `git submodule update --init` in the cloned repository's directory
3. Open ResForge.xcodeproj in Xcode 12.4
4. Product > Build

Everything compiles fine and compilation nearly finishes until we hit the problematic file I am referencing. The targetted scheme is "ResForge" and the build destination is "My Mac."

**Comment by andrews05** [comment]
Hi, thanks for the report. I've just pushed a commit which I think should fix this. Let me know if it works.

**Comment by ghost** [comment]
Your commit fixed the issue. Thank you so much!
