### ISSUE TITLE
Crash when opening BNDL

### ISSUE THREAD

**Issue by ryandesign** [andrews05/ResForge#7]
Hello, thank you for making ResForge! I just found it today and was trying it out. I opened the MacTCP 2.0.6 control panel in ResForge but when I tried to open a BNDL resource, ResForge crashed.

I'm running macOS 10.15.7 and ResForge 1.3.2. The crash log didn't look very helpful since there were no debug symbol names, so I recompiled it in Xcode 12.4 and ran it from there and it said:

```
Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value: file ResForge/ElementRSID.swift, line 80
```

**Comment by andrews05** [comment]
Hi, thanks for the report!
I can reproduce the error but haven't figured out the underlying cause yet (the message you show appears to be misleading). I'll keep investigating...

**Comment by andrews05** [comment]
Alright, I found the cause and pushed a commit to fix this, let me know if it works.

**Comment by ryandesign** [comment]
Thanks! I agree after 1dc86fc8809922f2d86ed8a335f73eefdc9fde47 it doesn't crash when opening the BNDL.
