### ISSUE TITLE
Support for AppleSingle and MacBinary formats

### ISSUE THREAD

**Issue by lorrden** [andrews05/ResForge#9]
There are a couple formats for transferring data with resource forks. Including formats like AppleSingle, AppleDouble and MacBinary (different versions).

In the AlephOne project for example, scenarios are typically converted to AppleSingle or MacBinary to enable Multiplatform use. It would be awesome if AppleSingle and MacBinary formats could be supported directly in ResForge.

- [x] MacBinary
- [x] AppleSingle
- [x] AppleDouble

**Comment by andrews05** [comment]
Hi, thanks for the suggestion. I think that's a great idea and will try to look into it sometime.

**Comment by andrews05** [comment]
@lorrden Quick question: Are you hoping for read/write support for these formats or will readonly suffice?

**Comment by andrews05** [comment]
I've just merged MacBinary support 🙂
This includes read/write support for MacBinary II and III files, though does not support creating new files.

Would be great if you could test this out and see if it works for you. There's no new release yet but I can send you a dev build if you need.

**Comment by lorrden** [comment]
I managed to build it, so far I was able to open a Marathon map and view the STR content of it. This looks very nice and promising 👍

**Comment by andrews05** [comment]
Good to hear!
Would you be able to direct me to some AppleSingle sample files, e.g. for AlephOne? I could create some of course but it would be helpful to have some "real life" examples.

**Comment by andrews05** [comment]
AppleSingle and Double support has been merged. I'll close this now but let me know if you encounter any issues.

**Comment by andrews05** [comment]
This is now published in v1.4: https://github.com/andrews05/ResForge/releases
